/** Static UI photos on Cloudinary, matched to SuqET categories and seed products. */

export const UI_PHOTOS = {
  hero: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781695/suqet/ui/hero-market.jpg',
  sell: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781722/suqet/ui/sell-market.jpg',
  samsung: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781697/suqet/ui/samsung-phone.jpg',
  kemis: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787784544/suqet/ui/habesha-kemis.jpg',
  table: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781698/suqet/ui/coffee-table.jpg',
  books: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787785916/suqet/ui/amharic-books.jpg',
  helmet: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781723/suqet/ui/moto-helmet.jpg',
  mitad: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781701/suqet/ui/injera-mitad.jpg',
  toolbox: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781702/suqet/ui/toolbox.jpg',
  laptop: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781702/suqet/ui/hp-laptop.jpg',
  bike: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781703/suqet/ui/kids-bike.jpg',
  sofa: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781704/suqet/ui/sofa.jpg',
  jebena: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787785918/suqet/ui/jebena.jpg',
  tv: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781959/suqet/ui/led-tv.jpg',
  guitar: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781960/suqet/ui/guitar.jpg',
  backpack: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781977/suqet/ui/backpack.jpg',
  camera: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781961/suqet/ui/camera.jpg',
  jacket: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787782826/suqet/ui/leather-jacket.jpg',
  chair: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781963/suqet/ui/office-chair.jpg',
  tablet: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781964/suqet/ui/tablet.jpg',
  netela: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787782824/suqet/ui/netela.jpg',
  stroller: 'https://res.cloudinary.com/dfghwzinf/image/upload/v1787781965/suqet/ui/stroller.jpg',
} as const;

export const CATEGORY_PHOTOS: Record<string, string> = {
  Electronics: UI_PHOTOS.samsung,
  Clothing: UI_PHOTOS.kemis,
  Furniture: UI_PHOTOS.sofa,
  Books: UI_PHOTOS.books,
  Vehicles: UI_PHOTOS.helmet,
  Kitchen: UI_PHOTOS.mitad,
  Tools: UI_PHOTOS.toolbox,
  Other: UI_PHOTOS.bike,
};

export interface CatalogItem {
  title: string;
  price: number;
  location: string;
  condition: 'new' | 'like_new' | 'good' | 'fair';
  image: string;
  category: string;
}

/** Names match the original SuqET seed catalog. */
export const DEMO_CATALOG: CatalogItem[] = [
  {
    title: 'Samsung Galaxy A14',
    price: 8500,
    location: 'Addis Ababa',
    condition: 'like_new',
    image: UI_PHOTOS.samsung,
    category: 'Electronics',
  },
  {
    title: 'Traditional Habesha Kemis',
    price: 4200,
    location: 'Addis Ababa',
    condition: 'good',
    image: UI_PHOTOS.kemis,
    category: 'Clothing',
  },
  {
    title: 'Wooden Coffee Table',
    price: 6500,
    location: 'Jimma',
    condition: 'good',
    image: UI_PHOTOS.table,
    category: 'Furniture',
  },
  {
    title: 'Amharic Novel Bundle',
    price: 900,
    location: 'Hawassa',
    condition: 'fair',
    image: UI_PHOTOS.books,
    category: 'Books',
  },
  {
    title: 'Yamaha Motorcycle Helmet',
    price: 2800,
    location: 'Addis Ababa',
    condition: 'like_new',
    image: UI_PHOTOS.helmet,
    category: 'Vehicles',
  },
  {
    title: 'Injera Mitad (Electric)',
    price: 3500,
    location: 'Hawassa',
    condition: 'good',
    image: UI_PHOTOS.mitad,
    category: 'Kitchen',
  },
  {
    title: 'Toolbox Set 48pcs',
    price: 2100,
    location: 'Jimma',
    condition: 'new',
    image: UI_PHOTOS.toolbox,
    category: 'Tools',
  },
  {
    title: 'HP Laptop 15s',
    price: 18500,
    location: 'Addis Ababa',
    condition: 'good',
    image: UI_PHOTOS.laptop,
    category: 'Electronics',
  },
  {
    title: 'Kids Bicycle',
    price: 3200,
    location: 'Jimma',
    condition: 'fair',
    image: UI_PHOTOS.bike,
    category: 'Other',
  },
  {
    title: 'Sofa Set 3-Seater',
    price: 12000,
    location: 'Addis Ababa',
    condition: 'good',
    image: UI_PHOTOS.sofa,
    category: 'Furniture',
  },
  {
    title: 'Jebena Coffee Pot',
    price: 1800,
    location: 'Jimma',
    condition: 'good',
    image: UI_PHOTOS.jebena,
    category: 'Kitchen',
  },
  {
    title: '32-inch LED TV',
    price: 9500,
    location: 'Addis Ababa',
    condition: 'like_new',
    image: UI_PHOTOS.tv,
    category: 'Electronics',
  },
  {
    title: 'Acoustic Guitar',
    price: 4500,
    location: 'Hawassa',
    condition: 'good',
    image: UI_PHOTOS.guitar,
    category: 'Other',
  },
  {
    title: 'School Backpack',
    price: 750,
    location: 'Addis Ababa',
    condition: 'fair',
    image: UI_PHOTOS.backpack,
    category: 'Other',
  },
  {
    title: 'Canon EOS Camera',
    price: 22000,
    location: 'Addis Ababa',
    condition: 'like_new',
    image: UI_PHOTOS.camera,
    category: 'Electronics',
  },
  {
    title: 'Leather Jacket',
    price: 3800,
    location: 'Addis Ababa',
    condition: 'good',
    image: UI_PHOTOS.jacket,
    category: 'Clothing',
  },
  {
    title: 'Office Chair',
    price: 2400,
    location: 'Jimma',
    condition: 'good',
    image: UI_PHOTOS.chair,
    category: 'Furniture',
  },
  {
    title: 'Samsung Tablet',
    price: 7200,
    location: 'Addis Ababa',
    condition: 'like_new',
    image: UI_PHOTOS.tablet,
    category: 'Electronics',
  },
  {
    title: 'Cotton Netela Shawl',
    price: 1100,
    location: 'Addis Ababa',
    condition: 'new',
    image: UI_PHOTOS.netela,
    category: 'Clothing',
  },
  {
    title: 'Baby Stroller',
    price: 3900,
    location: 'Hawassa',
    condition: 'fair',
    image: UI_PHOTOS.stroller,
    category: 'Other',
  },
];
